//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diva.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diva.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS not ready. 的當地語系化字串。
        /// </summary>
        public static string BnTrackText_GPSNotReady {
            get {
                return ResourceManager.GetString("BnTrackText_GPSNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose
        ///Destination 的當地語系化字串。
        /// </summary>
        public static string BtnChooseDestinationText {
            get {
                return ResourceManager.GetString("BtnChooseDestinationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click and Go 的當地語系化字串。
        /// </summary>
        public static string BtnFlyToText {
            get {
                return ResourceManager.GetString("BtnFlyToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Full
        ///Control 的當地語系化字串。
        /// </summary>
        public static string BtnFullControlText {
            get {
                return ResourceManager.GetString("BtnFullControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simplified
        ///Control 的當地語系化字串。
        /// </summary>
        public static string BtnSimplifiedControlText {
            get {
                return ResourceManager.GetString("BtnSimplifiedControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Follow Me 的當地語系化字串。
        /// </summary>
        public static string BtnTrackText {
            get {
                return ResourceManager.GetString("BtnTrackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnChangePassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnChangePassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnCreateAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnCreateAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnDeleteAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnDeleteAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_FontFamily {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_FontSizeAdjust {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelConfirmPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelConfirmPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelLoginAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelLoginAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelNewPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelNewPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change password for account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgChangePassword {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgCreateAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgDeleteAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        public static string DialogTitleWarning {
            get {
                return ResourceManager.GetString("DialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duplicated name assigned 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgDuplicatedName {
            get {
                return ResourceManager.GetString("DroneSetting_MsgDuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No name assigned. 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgNoName {
            get {
                return ResourceManager.GetString("DroneSetting_MsgNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid value 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgValueInvalid {
            get {
                return ResourceManager.GetString("DroneSetting_MsgValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.ApplyBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discard 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_DiscardBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.DiscardBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_EditBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.EditBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_NewBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.NewBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_RemoveBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.RemoveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Got param:  的當地語系化字串。
        /// </summary>
        public static string GotParam {
            get {
                return ResourceManager.GetString("GotParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WP Altitude 的當地語系化字串。
        /// </summary>
        public static string GuidedWPAltitude {
            get {
                return ResourceManager.GetString("GuidedWPAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Active drone is unavailable or not ready to fly. 的當地語系化字串。
        /// </summary>
        public static string MsgActiveUnavailableOrNotReady {
            get {
                return ResourceManager.GetString("MsgActiveUnavailableOrNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 arming throttle 的當地語系化字串。
        /// </summary>
        public static string MsgArming {
            get {
                return ResourceManager.GetString("MsgArming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Asking flight controller version. 的當地語系化字串。
        /// </summary>
        public static string MsgAskFlightControllerVersion {
            get {
                return ResourceManager.GetString("MsgAskFlightControllerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mission Saved 的當地語系化字串。
        /// </summary>
        public static string MsgBoxSaveMission {
            get {
                return ResourceManager.GetString("MsgBoxSaveMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can not establish connection
        ///
        ///{0} 的當地語系化字串。
        /// </summary>
        public static string MsgCannotEstablishConnection {
            get {
                return ResourceManager.GetString("MsgCannotEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 can not get position 的當地語系化字串。
        /// </summary>
        public static string MsgCantGetPosition {
            get {
                return ResourceManager.GetString("MsgCantGetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t open file! {0} 的當地語系化字串。
        /// </summary>
        public static string MsgCantOpenFile {
            get {
                return ResourceManager.GetString("MsgCantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This will clear your existing planned mission, Continue? 的當地語系化字串。
        /// </summary>
        public static string MsgConfirmClearExistingMission {
            get {
                return ResourceManager.GetString("MsgConfirmClearExistingMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string MsgConfirmTitle {
            get {
                return ResourceManager.GetString("MsgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Connect First! 的當地語系化字串。
        /// </summary>
        public static string MsgConnectFirst {
            get {
                return ResourceManager.GetString("MsgConnectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection failed. 的當地語系化字串。
        /// </summary>
        public static string MsgConnectionFailed {
            get {
                return ResourceManager.GetString("MsgConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your default altitude is not valid 的當地語系化字串。
        /// </summary>
        public static string MsgDefaultAltitudeInvalid {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You must set a default altitude 的當地語系化字串。
        /// </summary>
        public static string MsgDefaultAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect 的當地語系化字串。
        /// </summary>
        public static string MsgDialogConnect {
            get {
                return ResourceManager.GetString("MsgDialogConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done. 的當地語系化字串。
        /// </summary>
        public static string MsgDialogDone {
            get {
                return ResourceManager.GetString("MsgDialogDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading waypoints 的當地語系化字串。
        /// </summary>
        public static string MsgDialogDownloadWps {
            get {
                return ResourceManager.GetString("MsgDialogDownloadWps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Getting WP 的當地語系化字串。
        /// </summary>
        public static string MsgDialogGetWp {
            get {
                return ResourceManager.GetString("MsgDialogGetWp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 execute the mission 的當地語系化字串。
        /// </summary>
        public static string MsgDialogRotationExecute {
            get {
                return ResourceManager.GetString("MsgDialogRotationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 switch next drone, index: {0}. 的當地語系化字串。
        /// </summary>
        public static string MsgDialogRotationSwitch {
            get {
                return ResourceManager.GetString("MsgDialogRotationSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting params 的當地語系化字串。
        /// </summary>
        public static string MsgDialogSetParams {
            get {
                return ResourceManager.GetString("MsgDialogSetParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set total wps 的當地語系化字串。
        /// </summary>
        public static string MsgDialogSetTotalWps {
            get {
                return ResourceManager.GetString("MsgDialogSetTotalWps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting WP  的當地語系化字串。
        /// </summary>
        public static string MsgDialogSetWp {
            get {
                return ResourceManager.GetString("MsgDialogSetWp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uploading waypoints 的當地語系化字串。
        /// </summary>
        public static string MsgDialogUploadWps {
            get {
                return ResourceManager.GetString("MsgDialogUploadWps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You need at lease three drones online 的當地語系化字串。
        /// </summary>
        public static string MsgDroneNumberRequest {
            get {
                return ResourceManager.GetString("MsgDroneNumberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (None) 的當地語系化字串。
        /// </summary>
        public static string MsgDroneSettingNoPowerModel {
            get {
                return ResourceManager.GetString("MsgDroneSettingNoPowerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error reading kml file:  的當地語系化字串。
        /// </summary>
        public static string MsgErrorReadingKmlFile {
            get {
                return ResourceManager.GetString("MsgErrorReadingKmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed reading parameters, please check connection. 的當地語系化字串。
        /// </summary>
        public static string MsgFailedReadingParametersPleaseCheckConnection {
            get {
                return ResourceManager.GetString("MsgFailedReadingParametersPleaseCheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to send new fence points  的當地語系化字串。
        /// </summary>
        public static string MsgFailedToSendNewFencePoints {
            get {
                return ResourceManager.GetString("MsgFailedToSendNewFencePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loaded {0} 的當地語系化字串。
        /// </summary>
        public static string MsgFileLoaded {
            get {
                return ResourceManager.GetString("MsgFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FlyTo target not properly set. 的當地語系化字串。
        /// </summary>
        public static string MsgFlyToTargetNotProperlySet {
            get {
                return ResourceManager.GetString("MsgFlyToTargetNotProperlySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 done 的當地語系化字串。
        /// </summary>
        public static string MsgFormProgressDone {
            get {
                return ResourceManager.GetString("MsgFormProgressDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 mavlink connecting 的當地語系化字串。
        /// </summary>
        public static string MsgFormProgressMavlinkConnecting {
            get {
                return ResourceManager.GetString("MsgFormProgressMavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sync... 的當地語系化字串。
        /// </summary>
        public static string MsgFormProgressSync {
            get {
                return ResourceManager.GetString("MsgFormProgressSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 trying...{0} 的當地語系化字串。
        /// </summary>
        public static string MsgFormProgressTrying {
            get {
                return ResourceManager.GetString("MsgFormProgressTrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Canceled 的當地語系化字串。
        /// </summary>
        public static string MsgFormProgressUserCanceled {
            get {
                return ResourceManager.GetString("MsgFormProgressUserCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to get rally point 的當地語系化字串。
        /// </summary>
        public static string MsgGetRallyPointFailed {
            get {
                return ResourceManager.GetString("MsgGetRallyPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Getting Params.. (sysid {0} compid {1})  的當地語系化字串。
        /// </summary>
        public static string MsgGettingParams {
            get {
                return ResourceManager.GetString("MsgGettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You must have a home altitude 的當地語系化字串。
        /// </summary>
        public static string MsgHomeAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgHomeAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your home location is invalid 的當地語系化字串。
        /// </summary>
        public static string MsgHomeLocationInvalid {
            get {
                return ResourceManager.GetString("MsgHomeLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the height 的當地語系化字串。
        /// </summary>
        public static string MsgInputDialogHeightHint {
            get {
                return ResourceManager.GetString("MsgInputDialogHeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid coordinate, How did you do this? 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidCoordinate {
            get {
                return ResourceManager.GetString("MsgInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An invalid entry has been detected
        ///{0} 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidEntry {
            get {
                return ResourceManager.GetString("MsgInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Home or wp Alt 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidHomeOrWPAltitide {
            get {
                return ResourceManager.GetString("MsgInvalidHomeOrWPAltitide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &apos;{0}&apos; is not a valid power model name. 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidPowerModelName {
            get {
                return ResourceManager.GetString("MsgInvalidPowerModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Waypoint file 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidWaypointFile {
            get {
                return ResourceManager.GetString("MsgInvalidWaypointFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line invalid\n{0} 的當地語系化字串。
        /// </summary>
        public static string MsgLineInvalid {
            get {
                return ResourceManager.GetString("MsgLineInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot select computer as track source. Continue anyway? 的當地語系化字串。
        /// </summary>
        public static string MsgLocationApiNotReady {
            get {
                return ResourceManager.GetString("MsgLocationApiNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location API not ready yet 的當地語系化字串。
        /// </summary>
        public static string MsgLocationApiNotReadyTitle {
            get {
                return ResourceManager.GetString("MsgLocationApiNotReadyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low voltage level, Starting return to launch. 的當地語系化字串。
        /// </summary>
        public static string MsgLowVoltageWarning {
            get {
                return ResourceManager.GetString("MsgLowVoltageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload mission complete 的當地語系化字串。
        /// </summary>
        public static string MsgMissionAcceptWP {
            get {
                return ResourceManager.GetString("MsgMissionAcceptWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There are errors in your mission 的當地語系化字串。
        /// </summary>
        public static string MsgMissionError {
            get {
                return ResourceManager.GetString("MsgMissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload failed, mission was rejected by the Mav,\nitem had a bad option wp {0} {1} 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedBadWP {
            get {
                return ResourceManager.GetString("MsgMissionRejectedBadWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload wps failed {0} {1} 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedGeneral {
            get {
                return ResourceManager.GetString("MsgMissionRejectedGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload failed, please reduce the number of wp&apos;s 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedTooManyWaypoints {
            get {
                return ResourceManager.GetString("MsgMissionRejectedTooManyWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 mode: {0} 的當地語系化字串。
        /// </summary>
        public static string MsgModeChanged {
            get {
                return ResourceManager.GetString("MsgModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No available track source. 的當地語系化字串。
        /// </summary>
        public static string MsgNoAvailableTrackSource {
            get {
                return ResourceManager.GetString("MsgNoAvailableTrackSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 no connection 的當地語系化字串。
        /// </summary>
        public static string MsgNoConnection {
            get {
                return ResourceManager.GetString("MsgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No heartbeat received. 的當地語系化字串。
        /// </summary>
        public static string MsgNoHeartBeat {
            get {
                return ResourceManager.GetString("MsgNoHeartBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rally points - Nothing to download 的當地語系化字串。
        /// </summary>
        public static string MsgNoRallyPoint {
            get {
                return ResourceManager.GetString("MsgNoRallyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Power log file does not exist. 的當地語系化字串。
        /// </summary>
        public static string MsgPowerLogFileNotFound {
            get {
                return ResourceManager.GetString("MsgPowerLogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Home to loaded coordinate 的當地語系化字串。
        /// </summary>
        public static string MsgResetHomeCoordinate {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Homecoordinate 的當地語系化字串。
        /// </summary>
        public static string MsgResetHomeCoordinateTitle {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Row error 的當地語系化字串。
        /// </summary>
        public static string MsgRowError {
            get {
                return ResourceManager.GetString("MsgRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 reject by Mav {0} 的當地語系化字串。
        /// </summary>
        public static string MsgSaveWPRejected {
            get {
                return ResourceManager.GetString("MsgSaveWPRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 timeout on read, please try again. 的當地語系化字串。
        /// </summary>
        public static string MsgSaveWPTimeout {
            get {
                return ResourceManager.GetString("MsgSaveWPTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please set home first 的當地語系化字串。
        /// </summary>
        public static string MsgSetHomeFirst {
            get {
                return ResourceManager.GetString("MsgSetHomeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rotating 的當地語系化字串。
        /// </summary>
        public static string MsgStatusRotating {
            get {
                return ResourceManager.GetString("MsgStatusRotating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 status: takeoff 的當地語系化字串。
        /// </summary>
        public static string MsgTakedOff {
            get {
                return ResourceManager.GetString("MsgTakedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not Supported 的當地語系化字串。
        /// </summary>
        public static string MsgUnsupported {
            get {
                return ResourceManager.GetString("MsgUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port opened, waiting for heartbeat. 的當地語系化字串。
        /// </summary>
        public static string MsgWaitHeartBeat {
            get {
                return ResourceManager.GetString("MsgWaitHeartBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Waiting for switching mode to {0} 的當地語系化字串。
        /// </summary>
        public static string MsgWaitingForSwitchingTo {
            get {
                return ResourceManager.GetString("MsgWaitingForSwitchingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Drone must be actived. 的當地語系化字串。
        /// </summary>
        public static string MsgWarnDroneMustActive {
            get {
                return ResourceManager.GetString("MsgWarnDroneMustActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rotation mission have executing 的當地語系化字串。
        /// </summary>
        public static string MsgWarnRotationExcuteing {
            get {
                return ResourceManager.GetString("MsgWarnRotationExcuteing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low altitiude on WP#{0}
        ///Please reduce the altitude warning, or increase the altitude 的當地語系化字串。
        /// </summary>
        public static string MsgWarnWPAltitiude {
            get {
                return ResourceManager.GetString("MsgWarnWPAltitiude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///Packet lost for {0} seconds. 的當地語系化字串。
        /// </summary>
        public static string PacketLostForSeconds {
            get {
                return ResourceManager.GetString("PacketLostForSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click to activate drone 的當地語系化字串。
        /// </summary>
        public static string StrActivateDrone {
            get {
                return ResourceManager.GetString("StrActivateDrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Anonymous) 的當地語系化字串。
        /// </summary>
        public static string StrAnonymousAccount {
            get {
                return ResourceManager.GetString("StrAnonymousAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Base] 的當地語系化字串。
        /// </summary>
        public static string StrBase {
            get {
                return ResourceManager.GetString("StrBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 XML files|*.xml|All files|*.* 的當地語系化字串。
        /// </summary>
        public static string StrDroneSettingsFileExtensionFilter {
            get {
                return ResourceManager.GetString("StrDroneSettingsFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Energy consumption estimation failed. 的當地語系化字串。
        /// </summary>
        public static string StrEnergyConsumptionEstimationFailed {
            get {
                return ResourceManager.GetString("StrEnergyConsumptionEstimationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Estimated energy: {0:F2} mAh 的當地語系化字串。
        /// </summary>
        public static string StrEstimatedEnergy {
            get {
                return ResourceManager.GetString("StrEstimatedEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid power model and/or battery setting. 的當地語系化字串。
        /// </summary>
        public static string StrInvalidPowerModelAndOrBatterySetting {
            get {
                return ResourceManager.GetString("StrInvalidPowerModelAndOrBatterySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map Images|*.bmp;*.jpg;*.png 的當地語系化字串。
        /// </summary>
        public static string StrMapImageFileExternsionFilter {
            get {
                return ResourceManager.GetString("StrMapImageFileExternsionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No mission point available. 的當地語系化字串。
        /// </summary>
        public static string StrNoMissionPointAvailable {
            get {
                return ResourceManager.GetString("StrNoMissionPointAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log files|*.log|All files|*.* 的當地語系化字串。
        /// </summary>
        public static string StrPowerLogFileFilter {
            get {
                return ResourceManager.GetString("StrPowerLogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rally Point
        ///Alt: {0} 的當地語系化字串。
        /// </summary>
        public static string StrRallyPointToolTipText {
            get {
                return ResourceManager.GetString("StrRallyPointToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recalculating... 的當地語系化字串。
        /// </summary>
        public static string StrRecalculating {
            get {
                return ResourceManager.GetString("StrRecalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_FontFamily {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBAltitude_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBAltitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBBattery_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBBattery.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBGeoFence_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBGeoFence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBGroundSpeed_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBGroundSpeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Telemetry Data:  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBTitle_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBVerticalSpeed_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBVerticalSpeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connecting {0}... 的當地語系化字串。
        /// </summary>
        public static string TextFormProgressConnection {
            get {
                return ResourceManager.GetString("TextFormProgressConnection", resourceCulture);
            }
        }
    }
}
