//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diva.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diva.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_BtnChangePassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnChangePassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_BtnCreateAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnCreateAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_BtnDeleteAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnDeleteAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_FontFamily {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_FontSizeAdjust {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_LabelConfirmPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelConfirmPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_LabelLoginAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelLoginAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_LabelNewPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelNewPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigAccountPage_LabelPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password for account &apos;{0}&apos;?.
        /// </summary>
        public static string ConfigAccountPage_MsgChangePassword {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account &apos;{0}&apos;?.
        /// </summary>
        public static string ConfigAccountPage_MsgCreateAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account &apos;{0}&apos;?.
        /// </summary>
        public static string ConfigAccountPage_MsgDeleteAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_BtnBrowseIndoorMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnBrowseIndoorMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_BtnBrowseMapLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnBrowseMapLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_BtnMapConfigApply_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnMapConfigApply.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_BtnMapConfigReset_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnMapConfigReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_FontFamily {
            get {
                return ResourceManager.GetString("ConfigMapPage.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_FontSizeAdjust {
            get {
                return ResourceManager.GetString("ConfigMapPage.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelImageMapLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelImageMapLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelInitialPosition_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelInitialPosition.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelInitialZoom_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelInitialZoom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelIPLatitude_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelIPLatitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelIPLongtitude_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelIPLongtitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_LabelMapCacheLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelMapCacheLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_RBtnGlobalMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnGlobalMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfigMapPage_RBtnIndoorMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnIndoorMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arming throttle.
        /// </summary>
        public static string MsgArming {
            get {
                return ResourceManager.GetString("MsgArming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not establish a connection\n\n{0}.
        /// </summary>
        public static string MsgCannotEstablishConnection {
            get {
                return ResourceManager.GetString("MsgCannotEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not get position.
        /// </summary>
        public static string MsgCantGetPosition {
            get {
                return ResourceManager.GetString("MsgCantGetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open file! {0}.
        /// </summary>
        public static string MsgCantOpenFile {
            get {
                return ResourceManager.GetString("MsgCantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear your existing planned mission, Continue?.
        /// </summary>
        public static string MsgConfirmClearExistingMission {
            get {
                return ResourceManager.GetString("MsgConfirmClearExistingMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MsgConfirmTitle {
            get {
                return ResourceManager.GetString("MsgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your default altitude is not valid.
        /// </summary>
        public static string MsgDefaultAltitudeInvalid {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a default altitude.
        /// </summary>
        public static string MsgDefaultAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}.
        /// </summary>
        public static string MsgFileLoaded {
            get {
                return ResourceManager.GetString("MsgFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get rally point.
        /// </summary>
        public static string MsgGetRallyPointFailed {
            get {
                return ResourceManager.GetString("MsgGetRallyPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a home altitude.
        /// </summary>
        public static string MsgHomeAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgHomeAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your home location is invalid.
        /// </summary>
        public static string MsgHomeLocationInvalid {
            get {
                return ResourceManager.GetString("MsgHomeLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate, How did you do this?.
        /// </summary>
        public static string MsgInvalidCoordinate {
            get {
                return ResourceManager.GetString("MsgInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid entry has been detected\n{0}.
        /// </summary>
        public static string MsgInvalidEntry {
            get {
                return ResourceManager.GetString("MsgInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Home or wp Alt.
        /// </summary>
        public static string MsgInvalidHomeOrWPAltitide {
            get {
                return ResourceManager.GetString("MsgInvalidHomeOrWPAltitide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Waypoint file.
        /// </summary>
        public static string MsgInvalidWaypointFile {
            get {
                return ResourceManager.GetString("MsgInvalidWaypointFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line invalid\n{0}.
        /// </summary>
        public static string MsgLineInvalid {
            get {
                return ResourceManager.GetString("MsgLineInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in your mission.
        /// </summary>
        public static string MsgMissionError {
            get {
                return ResourceManager.GetString("MsgMissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed, mission was rejected by the Mav,\nitem had a bad option wp {0} {1}.
        /// </summary>
        public static string MsgMissionRejectedBadWP {
            get {
                return ResourceManager.GetString("MsgMissionRejectedBadWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload wps failed {0} {1}.
        /// </summary>
        public static string MsgMissionRejectedGeneral {
            get {
                return ResourceManager.GetString("MsgMissionRejectedGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed, please reduce the number of wp&apos;s.
        /// </summary>
        public static string MsgMissionRejectedTooManyWaypoints {
            get {
                return ResourceManager.GetString("MsgMissionRejectedTooManyWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode: {0}.
        /// </summary>
        public static string MsgModeChanged {
            get {
                return ResourceManager.GetString("MsgModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no connection.
        /// </summary>
        public static string MsgNoConnection {
            get {
                return ResourceManager.GetString("MsgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally points - Nothing to download.
        /// </summary>
        public static string MsgNoRallyPoint {
            get {
                return ResourceManager.GetString("MsgNoRallyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Home to loaded coordinate.
        /// </summary>
        public static string MsgResetHomeCoordinate {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Homecoordinate.
        /// </summary>
        public static string MsgResetHomeCoordinateTitle {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row error.
        /// </summary>
        public static string MsgRowError {
            get {
                return ResourceManager.GetString("MsgRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reject by Mav{0}.
        /// </summary>
        public static string MsgSaveWPRejected {
            get {
                return ResourceManager.GetString("MsgSaveWPRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeout on read, please try again..
        /// </summary>
        public static string MsgSaveWPTimeout {
            get {
                return ResourceManager.GetString("MsgSaveWPTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set home first.
        /// </summary>
        public static string MsgSetHomeFirst {
            get {
                return ResourceManager.GetString("MsgSetHomeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify video stream URI..
        /// </summary>
        public static string MsgSpecifyVideoURI {
            get {
                return ResourceManager.GetString("MsgSpecifyVideoURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status: takeoff.
        /// </summary>
        public static string MsgTakedOff {
            get {
                return ResourceManager.GetString("MsgTakedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        public static string MsgUnsupported {
            get {
                return ResourceManager.GetString("MsgUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for switching mode to {0}.
        /// </summary>
        public static string MsgWaitingForSwitchingTo {
            get {
                return ResourceManager.GetString("MsgWaitingForSwitchingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low altitiude on WP#{0}\nPlease reduce the altitude warning, or increase the altitude.
        /// </summary>
        public static string MsgWarnWPAltitiude {
            get {
                return ResourceManager.GetString("MsgWarnWPAltitiude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Anonymous).
        /// </summary>
        public static string StrAnonymousAccount {
            get {
                return ResourceManager.GetString("StrAnonymousAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally Point\nAlt: {0}.
        /// </summary>
        public static string StrRallyPointToolTipText {
            get {
                return ResourceManager.GetString("StrRallyPointToolTipText", resourceCulture);
            }
        }
    }
}
