//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diva.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diva.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnChangePassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnChangePassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnCreateAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnCreateAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_BtnDeleteAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.BtnDeleteAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_FontFamily {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_FontSizeAdjust {
            get {
                return ResourceManager.GetString("ConfigAccountPage.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelConfirmPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelConfirmPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelLoginAccount_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelLoginAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelNewPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelNewPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_LabelPassword_Text {
            get {
                return ResourceManager.GetString("ConfigAccountPage.LabelPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change password for account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgChangePassword {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgCreateAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete account &apos;{0}&apos;? 的當地語系化字串。
        /// </summary>
        public static string ConfigAccountPage_MsgDeleteAccount {
            get {
                return ResourceManager.GetString("ConfigAccountPage.MsgDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_BtnBrowseIndoorMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnBrowseIndoorMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_BtnBrowseMapLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnBrowseMapLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_BtnMapConfigApply_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnMapConfigApply.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_BtnMapConfigReset_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.BtnMapConfigReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_FontFamily {
            get {
                return ResourceManager.GetString("ConfigMapPage.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_FontSizeAdjust {
            get {
                return ResourceManager.GetString("ConfigMapPage.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelImageMapLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelImageMapLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelInitialPosition_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelInitialPosition.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelInitialZoom_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelInitialZoom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelIPLatitude_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelIPLatitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelIPLongtitude_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelIPLongtitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelMapCacheLocation_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelMapCacheLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelProxyPort_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelProxyPort.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_LabelProxySetting_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.LabelProxySetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_RBtnGlobalMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnGlobalMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_RBtnIndoorMap_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnIndoorMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_RBtnProxyCustom_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnProxyCustom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConfigMapPage_RBtnProxySystem_Text {
            get {
                return ResourceManager.GetString("ConfigMapPage.RBtnProxySystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        public static string DialogTitleWarning {
            get {
                return ResourceManager.GetString("DialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duplicated name assigned 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgDuplicatedName {
            get {
                return ResourceManager.GetString("DroneSetting_MsgDuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No name assigned. 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgNoName {
            get {
                return ResourceManager.GetString("DroneSetting_MsgNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid value 的當地語系化字串。
        /// </summary>
        public static string DroneSetting_MsgValueInvalid {
            get {
                return ResourceManager.GetString("DroneSetting_MsgValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.ApplyBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discard 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_DiscardBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.DiscardBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_EditBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.EditBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_FontFamily {
            get {
                return ResourceManager.GetString("DroneSettingInput.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_FontSizeAdjust {
            get {
                return ResourceManager.GetString("DroneSettingInput.FontSizeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_LabelBaudrate_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.LabelBaudrate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_LabelPortName_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.LabelPortName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_LabelPortNumber_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.LabelPortNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_LabelStreamURI_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.LabelStreamURI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_NewBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.NewBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string DroneSettingInput_RemoveBtn_Text {
            get {
                return ResourceManager.GetString("DroneSettingInput.RemoveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 arming throttle 的當地語系化字串。
        /// </summary>
        public static string MsgArming {
            get {
                return ResourceManager.GetString("MsgArming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can not establish a connection\n\n{0} 的當地語系化字串。
        /// </summary>
        public static string MsgCannotEstablishConnection {
            get {
                return ResourceManager.GetString("MsgCannotEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 can not get position 的當地語系化字串。
        /// </summary>
        public static string MsgCantGetPosition {
            get {
                return ResourceManager.GetString("MsgCantGetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t open file! {0} 的當地語系化字串。
        /// </summary>
        public static string MsgCantOpenFile {
            get {
                return ResourceManager.GetString("MsgCantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This will clear your existing planned mission, Continue? 的當地語系化字串。
        /// </summary>
        public static string MsgConfirmClearExistingMission {
            get {
                return ResourceManager.GetString("MsgConfirmClearExistingMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string MsgConfirmTitle {
            get {
                return ResourceManager.GetString("MsgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Connect First! 的當地語系化字串。
        /// </summary>
        public static string MsgConnectFirst {
            get {
                return ResourceManager.GetString("MsgConnectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} overlay has been imported 的當地語系化字串。
        /// </summary>
        public static string MsgCustomizeOverlayImport {
            get {
                return ResourceManager.GetString("MsgCustomizeOverlayImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your default altitude is not valid 的當地語系化字串。
        /// </summary>
        public static string MsgDefaultAltitudeInvalid {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You must set a default altitude 的當地語系化字串。
        /// </summary>
        public static string MsgDefaultAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgDefaultAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You need at lease three drones online 的當地語系化字串。
        /// </summary>
        public static string MsgDroneNumberRequest {
            get {
                return ResourceManager.GetString("MsgDroneNumberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loaded {0} 的當地語系化字串。
        /// </summary>
        public static string MsgFileLoaded {
            get {
                return ResourceManager.GetString("MsgFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to get rally point 的當地語系化字串。
        /// </summary>
        public static string MsgGetRallyPointFailed {
            get {
                return ResourceManager.GetString("MsgGetRallyPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You must have a home altitude 的當地語系化字串。
        /// </summary>
        public static string MsgHomeAltitudeRequired {
            get {
                return ResourceManager.GetString("MsgHomeAltitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your home location is invalid 的當地語系化字串。
        /// </summary>
        public static string MsgHomeLocationInvalid {
            get {
                return ResourceManager.GetString("MsgHomeLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid coordinate, How did you do this? 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidCoordinate {
            get {
                return ResourceManager.GetString("MsgInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An invalid entry has been detected\n{0} 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidEntry {
            get {
                return ResourceManager.GetString("MsgInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Home or wp Alt 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidHomeOrWPAltitide {
            get {
                return ResourceManager.GetString("MsgInvalidHomeOrWPAltitide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Waypoint file 的當地語系化字串。
        /// </summary>
        public static string MsgInvalidWaypointFile {
            get {
                return ResourceManager.GetString("MsgInvalidWaypointFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line invalid\n{0} 的當地語系化字串。
        /// </summary>
        public static string MsgLineInvalid {
            get {
                return ResourceManager.GetString("MsgLineInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low voltage level, Starting return to launch. 的當地語系化字串。
        /// </summary>
        public static string MsgLowVoltageWarning {
            get {
                return ResourceManager.GetString("MsgLowVoltageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload mission complete 的當地語系化字串。
        /// </summary>
        public static string MsgMissionAcceptWP {
            get {
                return ResourceManager.GetString("MsgMissionAcceptWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There are errors in your mission 的當地語系化字串。
        /// </summary>
        public static string MsgMissionError {
            get {
                return ResourceManager.GetString("MsgMissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload failed, mission was rejected by the Mav,\nitem had a bad option wp {0} {1} 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedBadWP {
            get {
                return ResourceManager.GetString("MsgMissionRejectedBadWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload wps failed {0} {1} 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedGeneral {
            get {
                return ResourceManager.GetString("MsgMissionRejectedGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload failed, please reduce the number of wp&apos;s 的當地語系化字串。
        /// </summary>
        public static string MsgMissionRejectedTooManyWaypoints {
            get {
                return ResourceManager.GetString("MsgMissionRejectedTooManyWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 mode: {0} 的當地語系化字串。
        /// </summary>
        public static string MsgModeChanged {
            get {
                return ResourceManager.GetString("MsgModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 no connection 的當地語系化字串。
        /// </summary>
        public static string MsgNoConnection {
            get {
                return ResourceManager.GetString("MsgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rally points - Nothing to download 的當地語系化字串。
        /// </summary>
        public static string MsgNoRallyPoint {
            get {
                return ResourceManager.GetString("MsgNoRallyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Home to loaded coordinate 的當地語系化字串。
        /// </summary>
        public static string MsgResetHomeCoordinate {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Homecoordinate 的當地語系化字串。
        /// </summary>
        public static string MsgResetHomeCoordinateTitle {
            get {
                return ResourceManager.GetString("MsgResetHomeCoordinateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Row error 的當地語系化字串。
        /// </summary>
        public static string MsgRowError {
            get {
                return ResourceManager.GetString("MsgRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 reject by Mav{0} 的當地語系化字串。
        /// </summary>
        public static string MsgSaveWPRejected {
            get {
                return ResourceManager.GetString("MsgSaveWPRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 timeout on read, please try again. 的當地語系化字串。
        /// </summary>
        public static string MsgSaveWPTimeout {
            get {
                return ResourceManager.GetString("MsgSaveWPTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please set home first 的當地語系化字串。
        /// </summary>
        public static string MsgSetHomeFirst {
            get {
                return ResourceManager.GetString("MsgSetHomeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Specify video stream URI. 的當地語系化字串。
        /// </summary>
        public static string MsgSpecifyVideoURI {
            get {
                return ResourceManager.GetString("MsgSpecifyVideoURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rotating 的當地語系化字串。
        /// </summary>
        public static string MsgStatusRotating {
            get {
                return ResourceManager.GetString("MsgStatusRotating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 status: takeoff 的當地語系化字串。
        /// </summary>
        public static string MsgTakedOff {
            get {
                return ResourceManager.GetString("MsgTakedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not Supported 的當地語系化字串。
        /// </summary>
        public static string MsgUnsupported {
            get {
                return ResourceManager.GetString("MsgUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Waiting for switching mode to {0} 的當地語系化字串。
        /// </summary>
        public static string MsgWaitingForSwitchingTo {
            get {
                return ResourceManager.GetString("MsgWaitingForSwitchingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low altitiude on WP#{0}\nPlease reduce the altitude warning, or increase the altitude 的當地語系化字串。
        /// </summary>
        public static string MsgWarnWPAltitiude {
            get {
                return ResourceManager.GetString("MsgWarnWPAltitiude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click to activate drone 的當地語系化字串。
        /// </summary>
        public static string strActivateDrone {
            get {
                return ResourceManager.GetString("strActivateDrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Anonymous) 的當地語系化字串。
        /// </summary>
        public static string StrAnonymousAccount {
            get {
                return ResourceManager.GetString("StrAnonymousAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;XML files|*.xml|All files|*.*&quot; 的當地語系化字串。
        /// </summary>
        public static string StrDroneSettingsFileExtensionFilter {
            get {
                return ResourceManager.GetString("StrDroneSettingsFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rally Point\nAlt: {0} 的當地語系化字串。
        /// </summary>
        public static string StrRallyPointToolTipText {
            get {
                return ResourceManager.GetString("StrRallyPointToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_FontFamily {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBAltitude_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBAltitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBBattery_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBBattery.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBGeoFence_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBGeoFence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBGroundSpeed_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBGroundSpeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Telemetry Data:  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBTitle_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string TelemetryDataPanel_GBVerticalSpeed_Text {
            get {
                return ResourceManager.GetString("TelemetryDataPanel.GBVerticalSpeed.Text", resourceCulture);
            }
        }
    }
}
